#!/usr/bin/env node
/* Render the diary from its single source into static HTML, and the
 * Experiment stat bar from its data files.
 *
 * Source:  website/content/diary.md — published entries, newest first.
 *          website/content/experiment/counters.json — the stat bar counters
 *            (composition, values, definitions for /experiment).
 *          website/content/hours.md, dollars.md — per-entry tallies; their
 *            sums OVERRIDE the hours/dollars values in counters.json (which
 *            is updated on disk so the two never disagree). Missing files
 *            mean "keep the current value" — nothing is invented.
 * Output:  website/diary.html  — every entry, full text, between
 *                                <!-- diary:begin --> / <!-- diary:end -->
 *          website/d/{slug}.html — one complete, independently shareable
 *                                entry with entry-specific social metadata
 *          website/index.html  — the CARD_COUNT most recent entries as cards
 *            (same markers) and the stat bar between
 *            <!-- counters:begin --> / <!-- counters:end -->.
 *          website/data/diary-og.json — title manifest for /api/og?slug=...
 *          website/assets/og/diary/{slug}-{hash}.png — static X image; the
 *            Open Graph image keeps using the dynamic endpoint.
 *
 * Run from the repository root after editing the markdown, commit the
 * regenerated pages together with it:
 *   node scripts/render-diary.mjs
 *
 * Entry format (hand-writable, nothing exotic):
 *
 *   ## {Title} — {DD Month YYYY}
 *
 *   Long-form body: paragraphs separated by blank lines. Supported inline
 *   markup: **bold**, `code`, [text](https://url). "- " lines form lists.
 *
 *   ---
 *   **Teaser:** one or two short sentences for the home-page card.
 *
 * The Teaser line is required — cards never truncate the body. With zero
 * entries the home page renders no card block at all and the diary page
 * keeps only its static note.
 */

import {
  readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, unlinkSync,
} from "node:fs";
import { createHash } from "node:crypto";
import { initWasm, Resvg } from "../functions/lib/resvg.js";
import { layoutTitle, renderDiaryOgSvg } from "../functions/lib/og-title.mjs";

const SOURCE = "website/content/diary.md";
const DIARY_PAGE = "website/diary.html";
const INDEX_PAGE = "website/index.html";
const COUNTERS_JSON = "website/content/experiment/counters.json";
const HOURS_FILE = "website/content/hours.md";
const DOLLARS_FILE = "website/content/dollars.md";
const ENTRY_TEMPLATE = "scripts/templates/diary-entry.html";
const ENTRY_DIR = "website/d";
const OG_MANIFEST = "website/data/diary-og.json";
const TWITTER_IMAGE_DIR = "website/assets/og/diary";
const RESVG_WASM = "functions/lib/resvg.wasm";
const CARD_COUNT = 6;
const BEGIN = "<!-- diary:begin -->";
const END = "<!-- diary:end -->";
const C_BEGIN = "<!-- counters:begin -->";
const C_END = "<!-- counters:end -->";
const J_BEGIN = "<!-- jsonld:begin -->";
const J_END = "<!-- jsonld:end -->";
const SITE = "https://byko.bykovas.lt";
const SITEMAP = "website/sitemap.xml";
const GENERATED_MARKER = "<!-- generated by scripts/render-diary.mjs; do not edit -->";
/* The manifest version covers dynamic /api/og cache invalidation. Static X
   image filenames are hashed from the final PNG bytes below, so an immutable
   URL can never silently point at changed pixels. */
const OG_FONT_PATHS = [
  "website/assets/fonts/Inter-SemiBold.ttf",
  "website/assets/fonts/JetBrainsMono-Regular.ttf",
];
const OG_CARD_INPUTS = [
  "functions/lib/og-title.mjs",
  "functions/lib/resvg.js",
  RESVG_WASM,
  ...OG_FONT_PATHS,
];
const OG_CARD_VERSION = OG_CARD_INPUTS.reduce(
  (hash, path) => hash.update(path).update("\0").update(readFileSync(path)).update("\0"),
  createHash("sha256")
).digest("hex").slice(0, 16);

const MONTHS = ["January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"];

function escapeHtml(text) {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;")
    .replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

/* The supported inline subset, applied after escaping. */
function inline(text) {
  return escapeHtml(text)
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/\[([^\]]+)\]\((https?:[^)\s]+)\)/g,
      '<a href="$2" target="_blank" rel="noopener">$1</a>');
}

function inlineToPlain(text) {
  return text
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\[([^\]]+)\]\((https?:[^)\s]+)\)/g, "$1")
    .replace(/\s+/g, " ").trim();
}

function slugify(title) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

function parseDate(text) {
  const match = /^(\d{1,2})\s+([A-Za-z]+)\s+(\d{4})$/.exec(text.trim());
  if (!match) return null;
  const month = MONTHS.findIndex(m => m.toLowerCase() === match[2].toLowerCase());
  if (month === -1) return null;
  return new Date(Date.UTC(Number(match[3]), month, Number(match[1])));
}

function bodyToHtml(lines) {
  const blocks = lines.join("\n").split(/\n{2,}/).map(b => b.trim()).filter(Boolean);
  const html = [];
  for (const block of blocks) {
    const rows = block.split("\n").map(r => r.trim());
    if (rows.every(r => r.startsWith("- "))) {
      html.push("<ul>" + rows.map(r => "<li>" + inline(r.slice(2)) + "</li>").join("") + "</ul>");
    } else {
      html.push("<p>" + inline(rows.join(" ")) + "</p>");
    }
  }
  return html.join("\n");
}

function parse(source) {
  /* strip HTML comments (the file may carry a format note at the top) */
  const text = source.replace(/<!--[\s\S]*?-->/g, "");
  const entries = [];
  const parts = text.split(/^## /m).slice(1);
  for (const part of parts) {
    const lines = part.split("\n");
    const header = lines.shift().trim();
    const sep = header.lastIndexOf(" — ");
    if (sep === -1) throw new Error(`entry header needs "{title} — {DD Month YYYY}": "## ${header}"`);
    const title = header.slice(0, sep).trim();
    const dateText = header.slice(sep + 3).trim();
    const date = parseDate(dateText);
    if (!date) throw new Error(`unparseable date "${dateText}" in "## ${header}"`);

    /* tail block: after the LAST "---" line, "**Key:** value" fields */
    let cut = -1;
    for (let i = lines.length - 1; i >= 0; i--) {
      if (lines[i].trim() === "---") { cut = i; break; }
    }
    if (cut === -1) throw new Error(`entry "${title}" is missing the --- field block`);
    const fields = {};
    for (const row of lines.slice(cut + 1)) {
      const match = /^\*\*([A-Za-z]+):\*\*\s*(.+)$/.exec(row.trim());
      if (match) fields[match[1].toLowerCase()] = match[2].trim();
    }
    if (!fields.teaser) throw new Error(`entry "${title}" is missing a "**Teaser:** ..." line`);

    entries.push({
      title, dateText, date,
      slug: slugify(title),
      teaser: fields.teaser,
      teaserText: inlineToPlain(fields.teaser),
      bodyHtml: bodyToHtml(lines.slice(0, cut)),
    });
  }
  entries.sort((a, b) => b.date - a.date); /* newest first, whatever the file order */
  return entries;
}

function prepareEntries(entries) {
  const slugs = new Map();
  for (const entry of entries) {
    if (!entry.slug) throw new Error(`entry "${entry.title}" produces an empty slug`);
    if (slugs.has(entry.slug)) {
      throw new Error(`entries "${slugs.get(entry.slug)}" and "${entry.title}" produce the same slug "${entry.slug}"`);
    }
    slugs.set(entry.slug, entry.title);
    /* Fail the site build rather than ever truncating a social-card title. */
    layoutTitle(entry.title);
    entry.imageVersion = createHash("sha256")
      .update(`${OG_CARD_VERSION}\0${entry.title}\0${entry.dateText}`)
      .digest("hex").slice(0, 12);
    entry.dateIso = entry.date.toISOString().slice(0, 10);
    entry.url = `${SITE}/d/${entry.slug}`;
    entry.ogImageUrl = `${SITE}/api/og?slug=${entry.slug}&v=${entry.imageVersion}`;
  }
}

async function renderTwitterImages(entries) {
  await initWasm(readFileSync(RESVG_WASM));
  const fonts = OG_FONT_PATHS.map(path => readFileSync(path));
  let totalBytes = 0;
  let removed = 0;
  mkdirSync(TWITTER_IMAGE_DIR, { recursive: true });
  for (const entry of entries) {
    const png = new Resvg(renderDiaryOgSvg(entry), {
      fitTo: { mode: "width", value: 1200 },
      font: {
        loadSystemFonts: false,
        fontBuffers: fonts,
        defaultFontFamily: "Inter",
      },
    }).render().asPng();
    entry.twitterImageVersion = createHash("sha256").update(png).digest("hex").slice(0, 12);
    entry.twitterImageFilename = `${entry.slug}-${entry.twitterImageVersion}.png`;
    entry.twitterImageUrl = `${SITE}/assets/og/diary/${entry.twitterImageFilename}`;
    writeFileSync(`${TWITTER_IMAGE_DIR}/${entry.twitterImageFilename}`, png);
    totalBytes += png.byteLength;
  }
  /* Keep older valid content-hashed files: already-published posts may still
     reference them. Remove only artifacts that predate content-hash naming,
     identified by a filename hash that does not match their actual bytes. */
  for (const item of readdirSync(TWITTER_IMAGE_DIR, { withFileTypes: true })) {
    if (!item.isFile() || !item.name.endsWith(".png")) continue;
    const match = /-([0-9a-f]{12})\.png$/.exec(item.name);
    const path = `${TWITTER_IMAGE_DIR}/${item.name}`;
    const actualHash = createHash("sha256").update(readFileSync(path)).digest("hex").slice(0, 12);
    if (!match || match[1] !== actualHash) {
      unlinkSync(path);
      removed++;
    }
  }
  return { count: entries.length, totalBytes, removed };
}

function safeJsonLd(value) {
  return JSON.stringify(value, null, 2).replace(/</g, "\\u003c");
}

function fillTemplate(template, replacements) {
  let page = template;
  for (const [key, value] of Object.entries(replacements)) {
    page = page.replaceAll(`{{${key}}}`, value);
  }
  const unresolved = page.match(/\{\{[A-Z0-9_]+\}\}/g);
  if (unresolved) throw new Error(`${ENTRY_TEMPLATE}: unresolved placeholders ${[...new Set(unresolved)].join(", ")}`);
  return page;
}

function renderEntryPages(entries) {
  const template = readFileSync(ENTRY_TEMPLATE, "utf8");
  const expected = new Set();
  const author = { "@type": "Person", "name": "Denisas Bykovas", "url": "https://bykovas.lt" };
  let removed = 0;
  mkdirSync(ENTRY_DIR, { recursive: true });

  for (const entry of entries) {
    const filename = `${entry.slug}.html`;
    const imageAlt = `BYKO Diary — ${entry.title}`;
    const jsonLd = {
      "@context": "https://schema.org",
      "@type": "BlogPosting",
      "@id": entry.url,
      "url": entry.url,
      "headline": entry.title,
      "description": entry.teaserText,
      "datePublished": entry.dateIso,
      "inLanguage": "en",
      "author": author,
      "isPartOf": { "@type": "Blog", "@id": `${SITE}/diary`, "url": `${SITE}/diary` },
      "image": { "@type": "ImageObject", "url": entry.ogImageUrl, "width": 1200, "height": 630 },
    };
    const page = fillTemplate(template, {
      GENERATED_MARKER,
      PAGE_TITLE: escapeHtml(entry.title),
      META_DESCRIPTION: escapeHtml(entry.teaserText),
      ENTRY_URL: escapeHtml(entry.url),
      OG_IMAGE_URL: escapeHtml(entry.ogImageUrl),
      TWITTER_IMAGE_URL: escapeHtml(entry.twitterImageUrl),
      IMAGE_ALT: escapeHtml(imageAlt),
      DATE_ISO: escapeHtml(entry.dateIso),
      DATE_TEXT: escapeHtml(entry.dateText),
      SLUG: escapeHtml(entry.slug),
      ENTRY_TITLE: inline(entry.title),
      ENTRY_BODY: entry.bodyHtml,
      JSON_LD: safeJsonLd(jsonLd),
    });
    writeFileSync(`${ENTRY_DIR}/${filename}`, page);
    expected.add(filename);
  }

  /* `website/d` is generator-owned. Only delete stale files carrying the
     generator marker; an unexpected hand-written page stops the run. */
  for (const item of readdirSync(ENTRY_DIR, { withFileTypes: true })) {
    if (!item.isFile() || !item.name.endsWith(".html") || expected.has(item.name)) continue;
    const path = `${ENTRY_DIR}/${item.name}`;
    if (!readFileSync(path, "utf8").includes(GENERATED_MARKER)) {
      throw new Error(`${path}: refusing to delete a stale page without the generator marker`);
    }
    unlinkSync(path);
    removed++;
  }
  return { count: expected.size, removed };
}

function replaceBetween(path, html, begin = BEGIN, end = END) {
  const page = readFileSync(path, "utf8");
  const i = page.indexOf(begin);
  const j = page.indexOf(end);
  if (i === -1 || j === -1 || j < i) {
    throw new Error(`${path}: markers ${begin} … ${end} not found`);
  }
  const inner = html ? "\n" + html + "\n" : "\n";
  writeFileSync(path, page.slice(0, i + begin.length) + inner + page.slice(j));
}

/* ---------- stat bar: counters.json + hours/dollars sums ---------- */

/* "- {title} — {number}" per line; sum of the numbers, null if no file. */
function sumTally(path) {
  if (!existsSync(path)) return null;
  const lines = readFileSync(path, "utf8").split("\n").map(l => l.trim()).filter(l => l.startsWith("- "));
  if (lines.length === 0) return null;
  let total = 0;
  for (const line of lines) {
    const sep = line.lastIndexOf(" — ");
    const num = sep === -1 ? NaN : parseFloat(line.slice(sep + 3).replace(/[^0-9.]/g, ""));
    if (isNaN(num)) throw new Error(`${path}: cannot parse "${line}" (expected "- {title} — {number}")`);
    total += num;
  }
  return total;
}

function renderCounters() {
  const today = new Date().toISOString().slice(0, 10);
  const data = JSON.parse(readFileSync(COUNTERS_JSON, "utf8"));
  if (!Array.isArray(data.counters) || data.counters.length === 0) {
    throw new Error(`${COUNTERS_JSON}: no counters`);
  }
  const sums = {
    hours: sumTally(HOURS_FILE),
    dollars: sumTally(DOLLARS_FILE),
  };
  let jsonChanged = false;
  for (const counter of data.counters) {
    const sum = sums[counter.id];
    if (sum === null || sum === undefined) continue;
    const value = counter.id === "hours"
      ? (Number.isInteger(sum) ? String(sum) : sum.toFixed(1)) + " h"
      : "$" + Math.round(sum);
    if (counter.value !== value) {
      counter.value = value;
      counter.asOf = today;
      jsonChanged = true;
    }
  }
  if (jsonChanged) writeFileSync(COUNTERS_JSON, JSON.stringify(data, null, 2) + "\n");
  const band = data.counters.map(counter =>
    `      <a class="${counter.kind === "spent" ? "blue" : "peach"}" href="experiment.html#${counter.id}"><b>${escapeHtml(counter.value)}</b><span>${escapeHtml(counter.label)}</span></a>`
  ).join("\n");
  return {
    html: `    <div class="exp-band">\n${band}\n    </div>`,
    count: data.counters.length,
    jsonChanged,
  };
}

const entries = parse(readFileSync(SOURCE, "utf8"));
prepareEntries(entries);
const twitterImages = await renderTwitterImages(entries);

/* /diary — every entry, full text */
const diaryHtml = entries.map(entry => `<article class="entry" id="${entry.slug}">
  <div class="entry-head">
    <h2><a href="/d/${entry.slug}">${inline(entry.title)}</a></h2>
    <span class="entry-date">${escapeHtml(entry.dateText)}</span>
  </div>
${entry.bodyHtml}
</article>`).join("\n");

/* home page — the CARD_COUNT most recent as cards; zero entries → no block */
const cards = entries.slice(0, CARD_COUNT).map(entry => `      <a class="card" href="/d/${entry.slug}">
        <span class="label">${escapeHtml(entry.dateText)}</span>
        <h3>${inline(entry.title)}</h3>
        <p>${inline(entry.teaser)}</p>
      </a>`).join("\n");
const indexHtml = entries.length ? `    <div class="cards3">\n${cards}\n    </div>` : "";

replaceBetween(DIARY_PAGE, diaryHtml);
replaceBetween(INDEX_PAGE, indexHtml);

const entryPages = renderEntryPages(entries);
writeFileSync(OG_MANIFEST, JSON.stringify({
  version: 1,
  entries: entries.map(entry => ({
    slug: entry.slug,
    title: entry.title,
    dateText: entry.dateText,
    datePublished: entry.dateIso,
    imageVersion: entry.imageVersion,
    twitterImageVersion: entry.twitterImageVersion,
  })),
}, null, 2) + "\n");

const counters = renderCounters();
replaceBetween(INDEX_PAGE, counters.html, C_BEGIN, C_END);

/* ---------- header navigation (one canonical menu on every page) ------- */

/* The current page's own item renders as a non-link with aria-current so
   the user still sees where they are. Items without `page` (index anchors)
   stay links everywhere, including on the home page itself. */
const NAV_ITEMS = [
  { label: "Referendum", href: "index.html#referendum" },
  { label: "Diary", href: "diary.html", page: "diary.html" },
  { label: "Facts", href: "index.html#facts" },
  { label: "Market", href: "market.html", page: "market.html" },
  { label: "Specification", href: "specification.html", page: "specification.html" },
];
const NAV_PAGES = [INDEX_PAGE, DIARY_PAGE, "website/experiment.html",
  "website/market.html", "website/specification.html"];

for (const path of NAV_PAGES) {
  const file = path.split("/").pop();
  const nav = NAV_ITEMS.map(item => item.page === file
    ? `      <span aria-current="page">${item.label}</span>`
    : `      <a href="${item.href}">${item.label}</a>`).join("\n");
  replaceBetween(path, nav, "<!-- nav:begin -->", "<!-- nav:end -->");
}

/* ---------- structured data + sitemap (same source, same run) ---------- */

const author = { "@type": "Person", "name": "Denisas Bykovas", "url": "https://bykovas.lt" };
const blogJson = {
  "@context": "https://schema.org",
  "@type": "Blog",
  "@id": `${SITE}/diary`,
  "url": `${SITE}/diary`,
  "name": "The diary of an honest token",
  "inLanguage": "en",
  "author": author,
  "blogPost": entries.map(entry => ({
    "@type": "BlogPosting",
    "headline": entry.title,
    "datePublished": entry.dateIso,
    "url": entry.url,
    "author": author,
  })),
};
replaceBetween(DIARY_PAGE,
  `<script type="application/ld+json">\n${safeJsonLd(blogJson)}\n</script>`,
  J_BEGIN, J_END);

const newest = entries.length ? entries[0].date.toISOString().slice(0, 10) : null;
const sitemapUrls = [
  { loc: `${SITE}/`, lastmod: newest },
  { loc: `${SITE}/diary`, lastmod: newest },
  ...entries.map(entry => ({ loc: entry.url, lastmod: entry.dateIso })),
  { loc: `${SITE}/market` },
  { loc: `${SITE}/specification` },
  { loc: `${SITE}/experiment` },
];
writeFileSync(SITEMAP,
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  sitemapUrls.map(u =>
    `  <url><loc>${u.loc}</loc>${u.lastmod ? `<lastmod>${u.lastmod}</lastmod>` : ""}</url>`
  ).join("\n") +
  `\n</urlset>\n`);

console.log(`rendered ${entries.length} entr${entries.length === 1 ? "y" : "ies"} → ${DIARY_PAGE}, ${entries.length ? Math.min(CARD_COUNT, entries.length) + " card(s)" : "no cards"} → ${INDEX_PAGE}`);
console.log(`entry pages: ${entryPages.count} → ${ENTRY_DIR}` + (entryPages.removed ? ` (${entryPages.removed} stale removed)` : ""));
console.log(`X images: ${twitterImages.count} static PNGs → ${TWITTER_IMAGE_DIR} (${twitterImages.totalBytes} bytes)` +
  (twitterImages.removed ? `; ${twitterImages.removed} invalid stale artifact(s) removed` : ""));
console.log(`stat bar: ${counters.count} counters` + (counters.jsonChanged ? " (counters.json values updated)" : ""));
