#!/usr/bin/env node
/* Render the diary from its single source into static HTML, and the
 * Experiment stat bar from its data files.
 *
 * Source:  website/content/diary.md — published entries, newest first.
 *          website/content/experiment/counters.json — the stat bar counters
 *            (composition, values, definitions for /experiment).
 *          website/content/hours.md, dollars.md — per-entry tallies; their
 *            sums OVERRIDE the hours/dollars values in counters.json (which
 *            is updated on disk so the two never disagree). Missing files
 *            mean "keep the current value" — nothing is invented.
 * Output:  website/diary.html  — every entry, full text, between
 *                                <!-- diary:begin --> / <!-- diary:end -->
 *          website/d/{slug}.html — one complete, independently shareable
 *                                entry with entry-specific social metadata
 *          website/index.html  — the CARD_COUNT most recent entries as cards
 *            (same markers) and the stat bar between
 *            <!-- counters:begin --> / <!-- counters:end -->.
 *          website/data/diary-og.json — title manifest for /api/og?slug=...
 *          website/assets/og/diary/{slug}-{hash}.png — static X image; the
 *            Open Graph image keeps using the dynamic endpoint.
 *
 * Run from the repository root after editing the markdown, commit the
 * regenerated pages together with it:
 *   node scripts/render-diary.mjs
 *
 * Entry format (hand-writable, nothing exotic):
 *
 *   ## {Title} — {DD Month YYYY}
 *
 *   Long-form body: paragraphs separated by blank lines. Supported inline
 *   markup: **bold**, `code`, [text](https://url) and [text](/path). "- " lines form lists.
 *
 *   ---
 *   **Teaser:** one or two short sentences for the home-page card.
 *
 * The Teaser line is required — cards never truncate the body. With zero
 * entries the home page renders no card block at all and the diary page
 * keeps only its static note.
 */

import {
  readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, unlinkSync,
} from "node:fs";
import { createHash } from "node:crypto";
import { initWasm, Resvg } from "../functions/lib/resvg.js";
import { layoutTitle, renderDiaryOgSvg, titleOptionsForEntry } from "../functions/lib/og-title.mjs";

const SOURCE = "website/content/diary.md";
const DIARY_PAGE = "website/diary.html";
const INDEX_PAGE = "website/index.html";
const COUNTERS_JSON = "website/content/experiment/counters.json";
const HOURS_FILE = "website/content/hours.md";
const DOLLARS_FILE = "website/content/dollars.md";
const ENTRY_TEMPLATE = "scripts/templates/diary-entry.html";
const ENTRY_DIR = "website/d";
const OG_MANIFEST = "website/data/diary-og.json";
const TWITTER_IMAGE_DIR = "website/assets/og/diary";
const RESVG_WASM = "functions/lib/resvg.wasm";
const CARD_COUNT = 6;
const BEGIN = "<!-- diary:begin -->";
const END = "<!-- diary:end -->";
const H_BEGIN = "<!-- hero:begin -->";
const H_END = "<!-- hero:end -->";
const C_BEGIN = "<!-- counters:begin -->";
const C_END = "<!-- counters:end -->";
const J_BEGIN = "<!-- jsonld:begin -->";
const J_END = "<!-- jsonld:end -->";
const SITE = "https://byko.bykovas.lt";
const SITEMAP = "website/sitemap.xml";
const GENERATED_MARKER = "<!-- generated by scripts/render-diary.mjs; do not edit -->";
/* The manifest version covers dynamic /api/og cache invalidation. Static X
   image filenames are hashed from the final PNG bytes below, so an immutable
   URL can never silently point at changed pixels. */
const OG_FONT_PATHS = [
  "website/assets/fonts/Archivo-Bold.ttf",
  "website/assets/fonts/Archivo-SemiBold.ttf",
  "website/assets/fonts/IBMPlexMono-Regular.ttf",
];
const OG_CARD_INPUTS = [
  "functions/lib/og-title.mjs",
  "functions/lib/resvg.js",
  RESVG_WASM,
  ...OG_FONT_PATHS,
];
const OG_CARD_VERSION = OG_CARD_INPUTS.reduce(
  (hash, path) => hash.update(path).update("\0").update(readFileSync(path)).update("\0"),
  createHash("sha256")
).digest("hex").slice(0, 16);

const MONTHS = ["January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"];

function escapeHtml(text) {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;")
    .replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

/* The supported inline subset, applied after escaping. */
function inline(text) {
  return escapeHtml(text)
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/\[([^\]]+)\]\((https?:[^)\s]+)\)/g,
      '<a href="$2" target="_blank" rel="noopener">$1</a>')
    /* Site-relative links stay in the tab: sending a reader to another page of
       the same diary through a new window is a bug, not a courtesy. */
    .replace(/\[([^\]]+)\]\((\/[^)\s]*)\)/g, '<a href="$2">$1</a>');
}

function inlineToPlain(text) {
  return text
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\[([^\]]+)\]\((https?:[^)\s]+)\)/g, "$1")
    .replace(/\[([^\]]+)\]\((\/[^)\s]*)\)/g, "$1")
    .replace(/\s+/g, " ").trim();
}

function slugify(title) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

function parseDate(text) {
  const match = /^(\d{1,2})\s+([A-Za-z]+)\s+(\d{4})$/.exec(text.trim());
  if (!match) return null;
  const month = MONTHS.findIndex(m => m.toLowerCase() === match[2].toLowerCase());
  if (month === -1) return null;
  return new Date(Date.UTC(Number(match[3]), month, Number(match[1])));
}

/* A standalone "![alt](/assets/diary/…)" line is a figure. Same-origin only:
   the site ships its own bytes, so a screenshot cannot rot or be swapped
   under us the way a hotlinked image can. */
const IMAGE_LINE = /^!\[([^\]]*)\]\((\/assets\/diary\/[^)\s]+)\)$/;

/* Intrinsic size straight from the file header — width/height on the tag is
   what keeps the page from jumping while a screenshot loads. */
function imageSize(path) {
  const bytes = readFileSync(path);
  if (bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))) {
    return { width: bytes.readUInt32BE(16), height: bytes.readUInt32BE(20) };
  }
  if (bytes.readUInt16BE(0) === 0xffd8) { /* JPEG: first SOFn frame header */
    for (let i = 2; i + 9 < bytes.length;) {
      if (bytes[i] !== 0xff) { i++; continue; }
      const marker = bytes[i + 1];
      if (marker >= 0xc0 && marker <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(marker)) {
        return { height: bytes.readUInt16BE(i + 5), width: bytes.readUInt16BE(i + 7) };
      }
      i += 2 + bytes.readUInt16BE(i + 2);
    }
  }
  throw new Error(`${path}: not a PNG or JPEG (diary images must be either)`);
}

function figureHtml(alt, src, title) {
  if (!alt.trim()) {
    throw new Error(`entry "${title}": image ${src} has no alt text — it is both the caption and what a screen reader announces`);
  }
  const path = `website${src}`;
  if (!existsSync(path)) throw new Error(`entry "${title}": image file ${path} does not exist`);
  const { width, height } = imageSize(path);
  return `<figure class="shot">`
    + `<img src="${escapeHtml(src)}" alt="${escapeHtml(alt)}" width="${width}" height="${height}"`
    + ` loading="lazy" decoding="async">`
    + `<figcaption>${inline(alt)}</figcaption></figure>`;
}

/* The optional "**Image:** ![alt](/assets/diary/{slug}/file)" tail field names a
   hero image: the lead on the entry page, a thumbnail in the list, and the
   right-hand panel of the OG card. It reuses the body-image syntax and rules —
   same-origin, PNG or JPEG, alt required — but is one designated picture, kept
   apart from the inline body screenshots. */
function parseHero(value, title) {
  const match = IMAGE_LINE.exec(value.trim());
  if (!match) {
    throw new Error(`entry "${title}": **Image:** must be "![alt](/assets/diary/{slug}/file.png)", got "${value}"`);
  }
  const [, alt, src] = match;
  if (!alt.trim()) throw new Error(`entry "${title}": hero image ${src} has no alt text`);
  const path = `website${src}`;
  if (!existsSync(path)) throw new Error(`entry "${title}": hero image file ${path} does not exist`);
  const { width, height } = imageSize(path);
  const mime = src.toLowerCase().endsWith(".png") ? "image/png" : "image/jpeg";
  return { src, alt, width, height, path, mime };
}

function bodyToHtml(lines, title) {
  const blocks = lines.join("\n").split(/\n{2,}/).map(b => b.trim()).filter(Boolean);
  const html = [];
  for (const block of blocks) {
    const rows = block.split("\n").map(r => r.trim());
    if (rows.every(r => IMAGE_LINE.test(r))) {
      html.push(rows.map(row => {
        const [, alt, src] = IMAGE_LINE.exec(row);
        return figureHtml(alt, src, title);
      }).join("\n"));
    } else if (rows.every(r => r.startsWith("- "))) {
      html.push("<ul>" + rows.map(r => "<li>" + inline(r.slice(2)) + "</li>").join("") + "</ul>");
    } else {
      /* A stray image line mixed into prose would silently print as text. */
      const stray = rows.find(r => r.startsWith("!["));
      if (stray) {
        throw new Error(`entry "${title}": image line must stand alone in its own paragraph — "${stray}"`);
      }
      html.push("<p>" + inline(rows.join(" ")) + "</p>");
    }
  }
  return html.join("\n");
}

function parse(source) {
  /* strip HTML comments (the file may carry a format note at the top) */
  const text = source.replace(/<!--[\s\S]*?-->/g, "");
  const entries = [];
  const parts = text.split(/^## /m).slice(1);
  for (const part of parts) {
    const lines = part.split("\n");
    const header = lines.shift().trim();
    const sep = header.lastIndexOf(" — ");
    if (sep === -1) throw new Error(`entry header needs "{title} — {DD Month YYYY}": "## ${header}"`);
    const title = header.slice(0, sep).trim();
    const dateText = header.slice(sep + 3).trim();
    const date = parseDate(dateText);
    if (!date) throw new Error(`unparseable date "${dateText}" in "## ${header}"`);

    /* tail block: after the LAST "---" line, "**Key:** value" fields */
    let cut = -1;
    for (let i = lines.length - 1; i >= 0; i--) {
      if (lines[i].trim() === "---") { cut = i; break; }
    }
    if (cut === -1) throw new Error(`entry "${title}" is missing the --- field block`);
    const fields = {};
    for (const row of lines.slice(cut + 1)) {
      const match = /^\*\*([A-Za-z]+):\*\*\s*(.+)$/.exec(row.trim());
      if (match) fields[match[1].toLowerCase()] = match[2].trim();
    }
    if (!fields.teaser) throw new Error(`entry "${title}" is missing a "**Teaser:** ..." line`);

    entries.push({
      title, dateText, date,
      slug: slugify(title),
      teaser: fields.teaser,
      teaserText: inlineToPlain(fields.teaser),
      hero: fields.image ? parseHero(fields.image, title) : null,
      bodyHtml: bodyToHtml(lines.slice(0, cut), title),
    });
  }
  entries.sort((a, b) => b.date - a.date); /* newest first, whatever the file order */
  return entries;
}

function prepareEntries(entries) {
  const slugs = new Map();
  for (const entry of entries) {
    if (!entry.slug) throw new Error(`entry "${entry.title}" produces an empty slug`);
    if (slugs.has(entry.slug)) {
      throw new Error(`entries "${slugs.get(entry.slug)}" and "${entry.title}" produce the same slug "${entry.slug}"`);
    }
    slugs.set(entry.slug, entry.title);
    /* Fail the site build rather than ever truncating a social-card title —
       with the same options the card renderer will use (a hero narrows it). */
    layoutTitle(entry.title, titleOptionsForEntry(entry));
    entry.imageVersion = createHash("sha256")
      .update(`${OG_CARD_VERSION}\0${entry.title}\0${entry.dateText}`)
      .digest("hex").slice(0, 12);
    entry.dateIso = entry.date.toISOString().slice(0, 10);
    entry.url = `${SITE}/d/${entry.slug}`;
    entry.ogImageUrl = `${SITE}/api/og?slug=${entry.slug}&v=${entry.imageVersion}`;
  }
}

async function renderTwitterImages(entries) {
  await initWasm(readFileSync(RESVG_WASM));
  const fonts = OG_FONT_PATHS.map(path => readFileSync(path));
  let totalBytes = 0;
  let removed = 0;
  mkdirSync(TWITTER_IMAGE_DIR, { recursive: true });
  for (const entry of entries) {
    /* Bake the hero into the card: read the committed file, inline it as a
       data URI, and let resvg cover-fit it into the panel. No resize library —
       the rasteriser does the scaling. */
    if (entry.hero) {
      entry.hero.dataUri = `data:${entry.hero.mime};base64,`
        + readFileSync(entry.hero.path).toString("base64");
    }
    const png = new Resvg(renderDiaryOgSvg(entry), {
      fitTo: { mode: "width", value: 1200 },
      font: {
        loadSystemFonts: false,
        fontBuffers: fonts,
        defaultFontFamily: "Archivo",
      },
    }).render().asPng();
    entry.twitterImageVersion = createHash("sha256").update(png).digest("hex").slice(0, 12);
    entry.twitterImageFilename = `${entry.slug}-${entry.twitterImageVersion}.png`;
    entry.twitterImageUrl = `${SITE}/assets/og/diary/${entry.twitterImageFilename}`;
    writeFileSync(`${TWITTER_IMAGE_DIR}/${entry.twitterImageFilename}`, png);
    totalBytes += png.byteLength;
  }
  /* Keep older valid content-hashed files: already-published posts may still
     reference them. Remove only artifacts that predate content-hash naming,
     identified by a filename hash that does not match their actual bytes. */
  for (const item of readdirSync(TWITTER_IMAGE_DIR, { withFileTypes: true })) {
    if (!item.isFile() || !item.name.endsWith(".png")) continue;
    const match = /-([0-9a-f]{12})\.png$/.exec(item.name);
    const path = `${TWITTER_IMAGE_DIR}/${item.name}`;
    const actualHash = createHash("sha256").update(readFileSync(path)).digest("hex").slice(0, 12);
    if (!match || match[1] !== actualHash) {
      unlinkSync(path);
      removed++;
    }
  }
  return { count: entries.length, totalBytes, removed };
}

function safeJsonLd(value) {
  return JSON.stringify(value, null, 2).replace(/</g, "\\u003c");
}

function fillTemplate(template, replacements) {
  let page = template;
  for (const [key, value] of Object.entries(replacements)) {
    page = page.replaceAll(`{{${key}}}`, value);
  }
  const unresolved = page.match(/\{\{[A-Z0-9_]+\}\}/g);
  if (unresolved) throw new Error(`${ENTRY_TEMPLATE}: unresolved placeholders ${[...new Set(unresolved)].join(", ")}`);
  return page;
}

function renderEntryPages(entries) {
  const template = readFileSync(ENTRY_TEMPLATE, "utf8");
  const expected = new Set();
  const author = { "@type": "Person", "name": "Denisas Bykovas", "url": "https://bykovas.lt" };
  let removed = 0;
  mkdirSync(ENTRY_DIR, { recursive: true });

  for (const [index, entry] of entries.entries()) {
    const filename = `${entry.slug}.html`;
    const imageAlt = `BYKO Diary — ${entry.title}`;
    /* entries are newest first, so the oldest episode is number one */
    const episode = entries.length - index;
    /* the entries either side of this one, newer first, as log rows */
    const neighbours = [entries[index - 1], entries[index + 1]]
      .filter(Boolean)
      .map((near, offset) => `      <a class="log-row" href="/d/${near.slug}">
        <span class="date">${escapeHtml(near.dateText)}</span>
        <span><h3>${inline(near.title)}</h3><p>${inline(near.teaser)}</p></span>
        <span class="ep">${offset === 0 && entries[index - 1] ? "newer" : "older"}</span>
      </a>`).join("\n");
    const jsonLd = {
      "@context": "https://schema.org",
      "@type": "BlogPosting",
      "@id": entry.url,
      "url": entry.url,
      "headline": entry.title,
      "description": entry.teaserText,
      "datePublished": entry.dateIso,
      "inLanguage": "en",
      "author": author,
      "isPartOf": { "@type": "Blog", "@id": `${SITE}/diary`, "url": `${SITE}/diary` },
      "image": { "@type": "ImageObject", "url": entry.twitterImageUrl, "width": 1200, "height": 630 },
    };
    /* The lead image: the whole picture, centred, not cropped — the list
       thumbnail and the OG card do the cropping, the entry shows it in full. */
    const heroHtml = entry.hero
      ? `<figure class="entry-hero"><img src="${escapeHtml(entry.hero.src)}" alt="${escapeHtml(entry.hero.alt)}"`
        + ` width="${entry.hero.width}" height="${entry.hero.height}" decoding="async"></figure>`
      : "";
    const page = fillTemplate(template, {
      GENERATED_MARKER,
      PAGE_TITLE: escapeHtml(entry.title),
      META_DESCRIPTION: escapeHtml(entry.teaserText),
      ENTRY_URL: escapeHtml(entry.url),
      /* Both crawlers get the baked static PNG (the hero is rendered into it);
         the dynamic /api/og cannot see the image bytes, and static is what X
         reliably fetches anyway. */
      OG_IMAGE_URL: escapeHtml(entry.twitterImageUrl),
      TWITTER_IMAGE_URL: escapeHtml(entry.twitterImageUrl),
      IMAGE_ALT: escapeHtml(imageAlt),
      DATE_ISO: escapeHtml(entry.dateIso),
      DATE_TEXT: escapeHtml(entry.dateText),
      SLUG: escapeHtml(entry.slug),
      ENTRY_TITLE: inline(entry.title),
      ENTRY_HERO: heroHtml,
      ENTRY_BODY: entry.bodyHtml,
      ENTRY_TEASER: inline(entry.teaser),
      EPISODE: `EP ${episode}`,
      NEIGHBOURS: neighbours,
      JSON_LD: safeJsonLd(jsonLd),
    });
    writeFileSync(`${ENTRY_DIR}/${filename}`, page);
    expected.add(filename);
  }

  /* `website/d` is generator-owned. Only delete stale files carrying the
     generator marker; an unexpected hand-written page stops the run. */
  for (const item of readdirSync(ENTRY_DIR, { withFileTypes: true })) {
    if (!item.isFile() || !item.name.endsWith(".html") || expected.has(item.name)) continue;
    const path = `${ENTRY_DIR}/${item.name}`;
    if (!readFileSync(path, "utf8").includes(GENERATED_MARKER)) {
      throw new Error(`${path}: refusing to delete a stale page without the generator marker`);
    }
    unlinkSync(path);
    removed++;
  }
  return { count: expected.size, removed };
}

function replaceBetween(path, html, begin = BEGIN, end = END) {
  const page = readFileSync(path, "utf8");
  const i = page.indexOf(begin);
  const j = page.indexOf(end);
  if (i === -1 || j === -1 || j < i) {
    throw new Error(`${path}: markers ${begin} … ${end} not found`);
  }
  const inner = html ? "\n" + html + "\n" : "\n";
  writeFileSync(path, page.slice(0, i + begin.length) + inner + page.slice(j));
}

/* ---------- stat bar: counters.json + hours/dollars sums ---------- */

/* "- {title} — {number}" per line; sum of the numbers, null if no file. */
function sumTally(path) {
  if (!existsSync(path)) return null;
  const lines = readFileSync(path, "utf8").split("\n").map(l => l.trim()).filter(l => l.startsWith("- "));
  if (lines.length === 0) return null;
  let total = 0;
  for (const line of lines) {
    const sep = line.lastIndexOf(" — ");
    const num = sep === -1 ? NaN : parseFloat(line.slice(sep + 3).replace(/[^0-9.]/g, ""));
    if (isNaN(num)) throw new Error(`${path}: cannot parse "${line}" (expected "- {title} — {number}")`);
    total += num;
  }
  return total;
}

function renderCounters() {
  const today = new Date().toISOString().slice(0, 10);
  const data = JSON.parse(readFileSync(COUNTERS_JSON, "utf8"));
  if (!Array.isArray(data.counters) || data.counters.length === 0) {
    throw new Error(`${COUNTERS_JSON}: no counters`);
  }
  const sums = {
    hours: sumTally(HOURS_FILE),
    dollars: sumTally(DOLLARS_FILE),
  };
  let jsonChanged = false;
  for (const counter of data.counters) {
    const sum = sums[counter.id];
    if (sum === null || sum === undefined) continue;
    const value = counter.id === "hours"
      ? (Number.isInteger(sum) ? String(sum) : sum.toFixed(1)) + " h"
      /* Cents only when there are cents: the diary quotes the exact figure,
         and a counter rounded away from it reads as a contradiction. */
      : "$" + (Number.isInteger(sum) ? sum : sum.toFixed(2));
    if (counter.value !== value) {
      counter.value = value;
      counter.asOf = today;
      jsonChanged = true;
    }
  }
  if (jsonChanged) writeFileSync(COUNTERS_JSON, JSON.stringify(data, null, 2) + "\n");
  /* "home": false keeps a counter defined and dated on /experiment while
     leaving it off the home page band, which holds six cells. */
  const onHome = data.counters.filter(counter => counter.home !== false);
  /* Provenance is the legend: a blue figure was read from the chain, a black
     one was counted by hand. Counters say which in counters.json. */
  const band = onHome.map(counter => {
    const chain = counter.provenance === "chain";
    return `      <a href="/experiment#${counter.id}">` +
      `<span class="figure${chain ? " live" : ""}">${escapeHtml(counter.value)}</span>` +
      `<span class="label">${escapeHtml(counter.label)}</span>` +
      `<span class="prov${chain ? " live" : ""}">${chain ? "from the chain" : "counted by hand"}</span></a>`;
  }).join("\n");
  return {
    html: `    <div class="counters">\n${band}\n    </div>`,
    count: onHome.length,
    total: data.counters.length,
    jsonChanged,
    /* the hero reads the same values, after the tally sums have been folded in */
    byId: new Map(data.counters.map((counter) => [counter.id, counter])),
  };
}

/* The three cells at the top of the home page. Their figures were hand-written
   HTML while the stat bar below them was generated, so they drifted: the hero
   said 99.5 h and $123.29 while the bar said 125.0 h and $165.29 — the same
   two claims, 25.5 hours and $42.00 apart, on one screen. Both now read the
   same counter values. Prose stays in counters.json; a {counter-id} inside it
   is substituted with that counter's value, so a number never gets typed
   twice. */
function renderHero(byId) {
  const data = JSON.parse(readFileSync(COUNTERS_JSON, "utf8"));
  const cells = data.hero?.cells;
  if (!Array.isArray(cells) || cells.length === 0) throw new Error(`${COUNTERS_JSON}: no hero cells`);
  const fill = (text) => text.replace(/\{([a-z-]+)\}/g, (whole, id) => {
    const counter = byId.get(id);
    if (!counter) throw new Error(`${COUNTERS_JSON}: hero refers to unknown counter "${id}"`);
    return counter.value;
  });
  const html = cells.map((cell) => {
    let figure;
    if (cell.live === "price") {
      /* index.js writes the live pool price into this span by id. */
      figure = `<div class="figure live"><span id="index-price-figure">0.000252</span></div>`;
    } else {
      const counter = byId.get(cell.counter);
      if (!counter) throw new Error(`${COUNTERS_JSON}: hero cell has unknown counter "${cell.counter}"`);
      figure = `<div class="figure">${escapeHtml(counter.value)}</div>`;
    }
    return `        <div${cell.live ? ' class="cell-live"' : ""}>\n` +
      `          ${figure}\n` +
      `          <span class="label">${escapeHtml(cell.label)}</span>\n` +
      `          <p class="say">${escapeHtml(fill(cell.say))}</p>\n` +
      `          <p class="tol">${escapeHtml(fill(cell.tol))}</p>\n` +
      `        </div>`;
  }).join("\n");
  return { html: `      <div class="band">\n${html}\n      </div>`, count: cells.length };
}

const entries = parse(readFileSync(SOURCE, "utf8"));
prepareEntries(entries);
const twitterImages = await renderTwitterImages(entries);

/* A thumbnail for the list surfaces. The link text already carries the title,
   so the picture is decorative here (empty alt); CSS cover-crops it. */
function listThumb(hero, className) {
  if (!hero) return "";
  return `<span class="${className}"><img src="${escapeHtml(hero.src)}" alt=""`
    + ` width="${hero.width}" height="${hero.height}" loading="lazy" decoding="async"></span>`;
}

/* /diary — the index: every entry as a log row, the text lives on /d/{slug} */
const diaryHtml = entries.map((entry, index) => `      <a class="log-row${entry.hero ? " has-thumb" : ""}" id="${entry.slug}" href="/d/${entry.slug}">
        <span class="date">${escapeHtml(entry.dateText)}</span>
        <span><h3>${inline(entry.title)}</h3><p>${inline(entry.teaser)}</p></span>
        <span class="ep-wrap"><span class="ep">EP ${entries.length - index}</span>${listThumb(entry.hero, "rthumb")}</span>
      </a>`).join("\n");

/* home page — the CARD_COUNT most recent as cards; zero entries → no block */
const cards = entries.slice(0, CARD_COUNT).map((entry, index) => `      <a class="card${entry.hero ? " has-thumb" : ""}" href="/d/${entry.slug}">
        ${listThumb(entry.hero, "thumb")}
        <span class="head"><span class="date">${escapeHtml(entry.dateText)}</span><span class="ep">EP ${entries.length - index}</span></span>
        <h3>${inline(entry.title)}</h3>
        <p>${inline(entry.teaser)}</p>
      </a>`).join("\n");
const indexHtml = entries.length ? `    <div class="cards3">\n${cards}\n    </div>` : "";

replaceBetween(DIARY_PAGE, diaryHtml);
replaceBetween(INDEX_PAGE, indexHtml);

const entryPages = renderEntryPages(entries);
writeFileSync(OG_MANIFEST, JSON.stringify({
  version: 1,
  entries: entries.map(entry => ({
    slug: entry.slug,
    title: entry.title,
    dateText: entry.dateText,
    datePublished: entry.dateIso,
    imageVersion: entry.imageVersion,
    twitterImageVersion: entry.twitterImageVersion,
  })),
}, null, 2) + "\n");

const counters = renderCounters();
replaceBetween(INDEX_PAGE, counters.html, C_BEGIN, C_END);
const hero = renderHero(counters.byId);
replaceBetween(INDEX_PAGE, hero.html, H_BEGIN, H_END);

/* ---------- header navigation (one canonical menu on every page) ------- */

/* The current page's own item renders as a non-link with aria-current so
   the user still sees where they are. Items without `page` (index anchors)
   stay links everywhere, including on the home page itself. */
const NAV_ITEMS = [
  { label: "Referendum", href: "/#referendum" },
  { label: "Diary", href: "/diary", page: "diary.html" },
  { label: "Facts", href: "/#facts" },
  { label: "Services", href: "/#services", className: "services" },
  { label: "Market", href: "/market", page: "market.html" },
  { label: "Specification", href: "/specification", page: "specification.html" },
];
/* ledger.html carries the same header as the rest and is kept in sync here,
   but it is deliberately absent from NAV_ITEMS: it is reached from the running
   experiments block and from the diary entry it belongs to, not from the nav. */
const NAV_PAGES = [INDEX_PAGE, DIARY_PAGE, "website/experiment.html",
  "website/market.html", "website/specification.html", "website/ledger.html",
  "website/self-trading.html"];

for (const path of NAV_PAGES) {
  const file = path.split("/").pop();
  /* Services carries the live accent in the header, on every page. */
  const nav = NAV_ITEMS.map(item => {
    const cls = item.className ? ` class="${item.className}"` : "";
    return item.page === file
      ? `      <span${cls} aria-current="page">${item.label}</span>`
      : `      <a${cls} href="${item.href}">${item.label}</a>`;
  }).join("\n");
  replaceBetween(path, nav, "<!-- nav:begin -->", "<!-- nav:end -->");
}

/* ---------- every page this run touched must still be balanced ----------
   An unbalanced <div> does not break the build, does not warn, and does not
   look wrong at the point of the mistake: one stray </div> after the hero
   closed the page wrapper early, and every section below it — six of them —
   silently lost its horizontal padding and ran to the edge of the screen on
   every viewport. Counting tags is crude, but it catches exactly that. */
function assertBalanced(path) {
  const html = readFileSync(path, "utf8");
  const open = (html.match(/<div\b/g) ?? []).length;
  const close = (html.match(/<\/div>/g) ?? []).length;
  if (open !== close) {
    throw new Error(`${path}: ${open} <div> against ${close} </div> — ` +
      `${open > close ? "something is left open" : "there is a stray close"}`);
  }
}

/* ---------- structured data + sitemap (same source, same run) ---------- */

const author = { "@type": "Person", "name": "Denisas Bykovas", "url": "https://bykovas.lt" };
const blogJson = {
  "@context": "https://schema.org",
  "@type": "Blog",
  "@id": `${SITE}/diary`,
  "url": `${SITE}/diary`,
  "name": "The diary of an honest token",
  "inLanguage": "en",
  "author": author,
  "blogPost": entries.map(entry => ({
    "@type": "BlogPosting",
    "headline": entry.title,
    "datePublished": entry.dateIso,
    "url": entry.url,
    "author": author,
  })),
};
replaceBetween(DIARY_PAGE,
  `<script type="application/ld+json">\n${safeJsonLd(blogJson)}\n</script>`,
  J_BEGIN, J_END);

const newest = entries.length ? entries[0].date.toISOString().slice(0, 10) : null;
const sitemapUrls = [
  { loc: `${SITE}/`, lastmod: newest },
  { loc: `${SITE}/diary`, lastmod: newest },
  ...entries.map(entry => ({ loc: entry.url, lastmod: entry.dateIso })),
  { loc: `${SITE}/market` },
  { loc: `${SITE}/specification` },
  { loc: `${SITE}/experiment` },
  { loc: `${SITE}/ledger` },
  { loc: `${SITE}/self-trading` },
];
writeFileSync(SITEMAP,
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  sitemapUrls.map(u =>
    `  <url><loc>${u.loc}</loc>${u.lastmod ? `<lastmod>${u.lastmod}</lastmod>` : ""}</url>`
  ).join("\n") +
  `\n</urlset>\n`);

console.log(`rendered ${entries.length} entr${entries.length === 1 ? "y" : "ies"} → ${DIARY_PAGE}, ${entries.length ? Math.min(CARD_COUNT, entries.length) + " card(s)" : "no cards"} → ${INDEX_PAGE}`);
console.log(`entry pages: ${entryPages.count} → ${ENTRY_DIR}` + (entryPages.removed ? ` (${entryPages.removed} stale removed)` : ""));
console.log(`X images: ${twitterImages.count} static PNGs → ${TWITTER_IMAGE_DIR} (${twitterImages.totalBytes} bytes)` +
  (twitterImages.removed ? `; ${twitterImages.removed} invalid stale artifact(s) removed` : ""));
for (const page of [INDEX_PAGE, DIARY_PAGE]) assertBalanced(page);
console.log(`hero band: ${hero.count} cells from the same counter values`);
console.log(`stat bar: ${counters.count} of ${counters.total} counters on the home page` + (counters.jsonChanged ? " (counters.json values updated)" : ""));
