import type { Claim, Env } from "../../shared/types";
import { today } from "./day";

/* The claims feed is the app's only external fact source. It lives on the
   site (CLAIMS_URL), CORS-open, regenerated by the diary publish flow. We
   pull it and cache it in KV for a minute so a burst of answers doesn't
   re-fetch it each time; the feed changes at most twice a day. */

const CACHE_KEY = "claims:feed:v1";
const CACHE_TTL_S = 60;

interface Feed {
  version: number;
  claims: Claim[];
}

function isClaim(value: unknown): value is Claim {
  if (typeof value !== "object" || value === null) return false;
  const c = value as Record<string, unknown>;
  return typeof c.id === "string" && typeof c.entry === "string" &&
    typeof c.text === "string" && typeof c.opens_at === "string";
}

export async function loadClaims(env: Env): Promise<Claim[]> {
  const cached = await env.KV.get(CACHE_KEY).catch(() => null);
  if (cached) {
    try {
      const feed = JSON.parse(cached) as Feed;
      if (Array.isArray(feed.claims)) return feed.claims.filter(isClaim);
    } catch { /* fall through to refetch */ }
  }

  const response = await fetch(env.CLAIMS_URL, { signal: AbortSignal.timeout(3_000) });
  if (!response.ok) throw new Error("claims feed unavailable");
  const feed = (await response.json()) as Feed;
  const claims = Array.isArray(feed.claims) ? feed.claims.filter(isClaim) : [];
  /* an empty or wrong-shaped feed is a broken deploy, not a truth — never
     cache it, never serve it as the state of the world */
  if (claims.length === 0) throw new Error("claims feed empty");
  await env.KV.put(CACHE_KEY, JSON.stringify({ version: 1, claims }), { expirationTtl: CACHE_TTL_S })
    .catch(() => { /* cache is best-effort */ });
  return claims;
}

/* Claims whose opens_at has arrived (UTC) — the ones a wallet may answer. */
export function openClaims(claims: Claim[]): Claim[] {
  const day = today();
  return claims.filter((claim) => claim.opens_at <= day);
}

/* Today's facts: the claims sharing the latest opens_at that is not in the
   future. Two per day by design. */
export function todaysFacts(claims: Claim[]): Claim[] {
  const open = openClaims(claims);
  if (open.length === 0) return [];
  const latest = open.reduce((max, c) => (c.opens_at > max ? c.opens_at : max), "");
  return open.filter((c) => c.opens_at === latest);
}

